// login
export const LOGIN_POST_LOGIN = "LOGIN_POST_LOGIN";
export const LOGIN_POST_LOGOUT = "LOGIN_POST_LOGOUT";
export const LOGIN_GET_FORGOT_PASSWORD = "LOGIN_GET_FORGOT_PASSWORD";
// register
export const REGISTER_POST_REGISTER = "REGISTER_POST_REGISTER";
// home
export const HOME_GET_TOP_DOC = "HOME_GET_TOP_DOC";
export const HOME_GET_TOP_DOCUMENT = "HOME_GET_TOP_DOCUMENT";
export const HOME_GET_ACCOUNT_INFO = "HOME_GET_ACCOUNT_INFO";
// doc
//// 1. For writer
export const DOC_POST_DOC = "DOC_POST_DOC";
export const DOC_GET_CATEGORY_DOC = "DOC_GET_CATEGORY_DOC";
export const DOC_GET_SUBJECT = "DOC_GET_SUBJECT";
//// 2. For reader
export const DOC_POST_LIKE_DOC = "DOC_POST_LIKE_DOC";
export const DOC_POST_COMMENT_DOC = "DOC_POST_COMMENT_DOC";
export const DOC_GET_TOP_DOC_BY_PAGE = "DOC_GET_TOP_DOC_BY_PAGE";
export const DOC_GET_TOP_DOC_BY_ID = "DOC_GET_TOP_DOC_BY_ID";
// post
//// 1. For writer
export const POST_POST_POST = "POST_POST_POST";
export const POST_GET_CATEGORY_POST = "POST_GET_CATEGORY_POST";
export const POST_GET_HASHTAG = "POST_GET_HASHTAG";
//// 2. For reader
export const POST_POST_LIKE_POST = "POST_POST_LIKE_POST";
export const POST_POST_COMMENT_POST = "POST_POST_COMMENT_POST";
export const POST_GET_TOP_POST_BY_PAGE = "POST_GET_TOP_POST_BY_PAGE";
export const POST_GET_TOP_POST_BY_ID = "POST_GET_TOP_POST_BY_ID";